name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Set up Java JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install System Dependencies
      run: |
        sudo apt update
        sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev libsqlite3-dev tk-dev libgdbm-compat-dev liblzma-dev lld

    - name: Install Python Package Tools
      run: |
        pip install --upgrade pip
        pip install Cython==0.29.33 buildozer

    - name: Build APK with Buildozer
      run: |
        yes | buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: package
        path: .buildozer/android/platform/build-arm64-v8a_armeabi-v7a/dists/*/bin/*.apk
